import { useState, useEffect, useRef, useCallback } from "react";
import { useLocation } from "wouter";
import { Presentation, Download, RefreshCw, ArrowLeft, ImageIcon, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { ProgressBar } from "@/components/presentation/ProgressBar";
import { SlidePreview } from "@/components/presentation/SlidePreview";
import { type Slide } from "@/components/presentation/SlideCard";
import { ThemeToggle } from "@/components/presentation/ThemeToggle";
import { useToast } from "@/hooks/use-toast";
import { presentationThemes, type ThemeId } from "@shared/schema";
import { generateSlides as apiGenerateSlides } from "@/lib/slides-api";

type PageState = "processing" | "results";

export default function Generate() {
  const [, navigate] = useLocation();
  const { toast } = useToast();
  
  const [pageState, setPageState] = useState<PageState>("processing");
  const [progress, setProgress] = useState(0);
  const [status, setStatus] = useState("");
  const [slides, setSlides] = useState<Slide[]>([]);
  const [currentSlideIndex, setCurrentSlideIndex] = useState(0);
  const [generatingImageFor, setGeneratingImageFor] = useState<string | null>(null);
  const [autoGeneratingImages, setAutoGeneratingImages] = useState(false);
  const [imageProgress, setImageProgress] = useState({ current: 0, total: 0 });
  const abortControllerRef = useRef<AbortController | null>(null);
  const hasAutoGeneratedRef = useRef(false);
  const imageGenerationTokenRef = useRef(0);
  
  const storedData = typeof window !== 'undefined' ? sessionStorage.getItem('slideGeneratorData') : null;
  const parsedData = storedData ? JSON.parse(storedData) : null;
  const selectedTheme: ThemeId = parsedData?.theme || "modern";

  useEffect(() => {
    if (!parsedData) {
      navigate("/");
      return;
    }
    
    generateSlides();
  }, []);

  const generateSlides = async () => {
    if (!parsedData) return;
    
    hasAutoGeneratedRef.current = false;
    imageGenerationTokenRef.current += 1;
    setSlides([]);
    setAutoGeneratingImages(false);
    abortControllerRef.current = new AbortController();
    setPageState("processing");
    setProgress(0);
    setStatus("Preparing content...");

    try {
      setProgress(30);
      setStatus("Generating slides with AI...");
      
      const generateData = await apiGenerateSlides({
        pdfText: parsedData.content,
        slideCount: parsedData.outline?.length || parsedData.slideCount,
        language: parsedData.language,
        theme: parsedData.theme,
        contentDensity: parsedData.contentDensity,
        outline: parsedData.outline,
      }, abortControllerRef.current.signal);

      setProgress(90);
      setStatus("Formatting presentation...");
      await new Promise(r => setTimeout(r, 300));
      
      setProgress(100);
      setStatus("Complete!");
      
      setTimeout(() => {
        setSlides(generateData.slides);
        setCurrentSlideIndex(0);
        setPageState("results");
      }, 500);

    } catch (error: any) {
      if (error.name === "AbortError") return;
      
      toast({
        title: "Generation Failed",
        description: error.message || "An error occurred",
        variant: "destructive",
      });
      navigate("/customize");
    }
  };

  const handleBack = () => {
    if (abortControllerRef.current) {
      abortControllerRef.current.abort();
    }
    navigate("/customize");
  };

  const handleNewPresentation = () => {
    sessionStorage.removeItem('slideGeneratorData');
    navigate("/");
  };

  const generateImageForSlide = async (slide: Slide): Promise<{ slideId: string; url: string; prompt: string } | null> => {
    try {
      const slideContent = slide.content || slide.bullets?.join(", ") || slide.subtitle || "";
      
      const response = await fetch("/api/generate-image", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          slideTitle: slide.title,
          slideContent: slideContent,
          slideType: slide.type,
          theme: selectedTheme,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        console.error(`Image generation failed for slide ${slide.id}:`, data.error);
        return null;
      }

      return { slideId: slide.id, url: data.url, prompt: data.prompt };
    } catch (error) {
      console.error(`Image generation error for slide ${slide.id}:`, error);
      return null;
    }
  };

  const autoGenerateAllImages = async (slidesToProcess: Slide[]) => {
    const slidesNeedingImages = slidesToProcess.filter(s => !s.image?.url);
    if (slidesNeedingImages.length === 0) return;

    const currentToken = imageGenerationTokenRef.current;
    setAutoGeneratingImages(true);
    setImageProgress({ current: 0, total: slidesNeedingImages.length });

    for (let i = 0; i < slidesNeedingImages.length; i++) {
      if (imageGenerationTokenRef.current !== currentToken) {
        return;
      }
      
      const slide = slidesNeedingImages[i];
      setImageProgress({ current: i + 1, total: slidesNeedingImages.length });
      
      const result = await generateImageForSlide(slide);
      
      if (result && imageGenerationTokenRef.current === currentToken) {
        setSlides(prev => prev.map(s => 
          s.id === result.slideId 
            ? { ...s, image: { url: result.url, prompt: result.prompt } }
            : s
        ));
      }
    }

    if (imageGenerationTokenRef.current === currentToken) {
      setAutoGeneratingImages(false);
    }
  };

  useEffect(() => {
    if (slides.length > 0 && pageState === "results" && !hasAutoGeneratedRef.current) {
      hasAutoGeneratedRef.current = true;
      autoGenerateAllImages(slides);
    }
  }, [slides, pageState]);

  const handleGenerateImage = async (slideId: string) => {
    const slide = slides.find(s => s.id === slideId);
    if (!slide) return;

    setGeneratingImageFor(slideId);

    const result = await generateImageForSlide(slide);
    
    if (result) {
      setSlides(prev => prev.map(s => 
        s.id === result.slideId 
          ? { ...s, image: { url: result.url, prompt: result.prompt } }
          : s
      ));
      toast({
        title: "Image Generated",
        description: "AI image has been added to the slide",
      });
    } else {
      toast({
        title: "Image Generation Failed",
        description: "Could not generate image for this slide",
        variant: "destructive",
      });
    }
    
    setGeneratingImageFor(null);
  };

  const handleExport = async () => {
    const pptxgenjs = await import("pptxgenjs");
    const pptx = new pptxgenjs.default();
    
    const theme = presentationThemes[selectedTheme];
    
    const parseColorWithAlpha = (color: string): { hex: string; alpha: number } => {
      if (color.startsWith('rgba')) {
        const match = color.match(/rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([0-9.]+)\s*\)/);
        if (match) {
          const r = parseInt(match[1]).toString(16).padStart(2, '0');
          const g = parseInt(match[2]).toString(16).padStart(2, '0');
          const b = parseInt(match[3]).toString(16).padStart(2, '0');
          const alpha = parseFloat(match[4]);
          return { hex: `${r}${g}${b}`, alpha };
        }
      }
      if (color.startsWith('rgb')) {
        const match = color.match(/rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)/);
        if (match) {
          const r = parseInt(match[1]).toString(16).padStart(2, '0');
          const g = parseInt(match[2]).toString(16).padStart(2, '0');
          const b = parseInt(match[3]).toString(16).padStart(2, '0');
          return { hex: `${r}${g}${b}`, alpha: 1 };
        }
      }
      return { hex: color.replace(/^#/, ''), alpha: 1 };
    };
    
    const parseColor = (color: string): string => parseColorWithAlpha(color).hex;
    
    const generateGradientBackground = (gradientStr: string): string => {
      const canvas = document.createElement('canvas');
      canvas.width = 1920;
      canvas.height = 1080;
      const ctx = canvas.getContext('2d');
      if (!ctx) return '';
      
      const angleMatch = gradientStr.match(/(\d+)deg/);
      const angle = angleMatch ? parseInt(angleMatch[1]) : 135;
      
      const colorStops: { color: string; position: number }[] = [];
      
      const withPercentRegex = /(#[a-fA-F0-9]{6}|#[a-fA-F0-9]{3}|rgba?\([^)]+\))\s+(\d+)%/g;
      let match;
      while ((match = withPercentRegex.exec(gradientStr)) !== null) {
        colorStops.push({ color: match[1], position: parseInt(match[2]) / 100 });
      }
      
      if (colorStops.length < 2) {
        const colorOnlyRegex = /#[a-fA-F0-9]{6}|#[a-fA-F0-9]{3}|rgba?\([^)]+\)/g;
        const colors: string[] = [];
        let colorMatch;
        while ((colorMatch = colorOnlyRegex.exec(gradientStr)) !== null) {
          colors.push(colorMatch[0]);
        }
        if (colors.length >= 2) {
          colors.forEach((color, i) => {
            colorStops.push({ color, position: i / (colors.length - 1) });
          });
        }
      }
      
      if (colorStops.length < 2) {
        ctx.fillStyle = theme.primary;
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        return canvas.toDataURL('image/png');
      }
      
      const radians = (angle - 90) * (Math.PI / 180);
      const cx = canvas.width / 2;
      const cy = canvas.height / 2;
      const diagonal = Math.sqrt(canvas.width * canvas.width + canvas.height * canvas.height) / 2;
      const x1 = cx - Math.cos(radians) * diagonal;
      const y1 = cy - Math.sin(radians) * diagonal;
      const x2 = cx + Math.cos(radians) * diagonal;
      const y2 = cy + Math.sin(radians) * diagonal;
      
      const gradient = ctx.createLinearGradient(x1, y1, x2, y2);
      colorStops.forEach(stop => {
        gradient.addColorStop(stop.position, stop.color);
      });
      
      ctx.fillStyle = gradient;
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      
      return canvas.toDataURL('image/png');
    };
    
    const gradientImage = generateGradientBackground(theme.gradient);
    
    const primaryColor = parseColor(theme.primary);
    const titleColor = parseColor(theme.titleColor);
    const textColor = parseColor(theme.text);
    const secondaryTextColor = parseColor(theme.textSecondary);
    const buttonBgColor = parseColor(theme.buttonBg);
    const buttonTextColor = parseColor(theme.buttonText);
    
    for (const slide of slides) {
      const pptxSlide = pptx.addSlide();
      
      if (gradientImage) {
        pptxSlide.background = { data: gradientImage };
      } else {
        pptxSlide.background = { color: parseColor(theme.primary) };
      }
      
      const hasImage = !!slide.image?.url;
      const textWidth = hasImage ? 5 : 9;
      const imageX = 5.5;
      const imageW = 4;
      const imageH = 4;
      const imageY = 1;
      
      if (slide.type === "title") {
        pptxSlide.addText(slide.title, { 
          x: 0.5, y: 2, w: hasImage ? 5 : 9, h: 1.5, 
          fontSize: 36, bold: true, align: hasImage ? "left" : "center", color: titleColor
        });
        if (slide.subtitle) {
          pptxSlide.addText(slide.subtitle, { 
            x: 0.5, y: 3.5, w: hasImage ? 5 : 9, h: 0.75, 
            fontSize: 20, align: hasImage ? "left" : "center", color: secondaryTextColor
          });
        }
      } else if (slide.type === "content") {
        pptxSlide.addText(slide.title, { 
          x: 0.5, y: 0.5, w: textWidth, h: 0.75, 
          fontSize: 28, bold: true, color: titleColor
        });
        if (slide.content) {
          pptxSlide.addText(slide.content, { 
            x: 0.5, y: 1.5, w: textWidth, h: 3.5, 
            fontSize: 16, color: secondaryTextColor
          });
        }
      } else if (slide.type === "bullets") {
        pptxSlide.addText(slide.title, { 
          x: 0.5, y: 0.5, w: textWidth, h: 0.75, 
          fontSize: 28, bold: true, color: titleColor
        });
        if (slide.bullets && slide.bullets.length > 0) {
          const bulletStyle = slide.bulletStyle || "bullet";
          
          const bulletRows = slide.bullets.map((bullet, i) => {
            let prefix = "•";
            if (bulletStyle === "numbered") prefix = `${i + 1}.`;
            else if (bulletStyle === "checkmark") prefix = "✓";
            else if (bulletStyle === "arrow") prefix = "→";
            else if (bulletStyle === "star") prefix = "★";
            
            return {
              text: `${prefix} ${bullet}`,
              options: { 
                fontSize: 14, 
                color: textColor,
                bullet: false,
                paraSpaceAfter: 10,
                breakLine: true
              }
            };
          });
          
          pptxSlide.addText(bulletRows, { 
            x: 0.5, y: 1.4, w: textWidth - 0.25, h: 3.8, 
            valign: 'top'
          });
        }
      } else if (slide.type === "steps") {
        pptxSlide.addText(slide.title, { 
          x: 0.5, y: 0.5, w: textWidth, h: 0.75, 
          fontSize: 28, bold: true, color: titleColor
        });
        if (slide.steps) {
          const stepHeight = 0.7;
          const chevronWidth = 0.55;
          const chevronHeight = 0.45;
          const startY = 1.4;
          
          slide.steps.forEach((step, i) => {
            const yPos = startY + (i * stepHeight);
            
            pptxSlide.addShape(pptx.ShapeType.chevron, {
              x: 0.5,
              y: yPos,
              w: chevronWidth,
              h: chevronHeight,
              fill: { color: buttonBgColor },
              line: { color: buttonBgColor, width: 0 },
            });
            
            pptxSlide.addText(String(i + 1), {
              x: 0.5,
              y: yPos,
              w: chevronWidth,
              h: chevronHeight,
              align: "center",
              valign: "middle",
              fontSize: 12,
              bold: true,
              color: buttonTextColor,
            });
            
            pptxSlide.addText(step.label, { 
              x: 1.15, y: yPos, w: textWidth - 0.65, h: 0.25, 
              fontSize: 13, bold: true, color: titleColor
            });
            pptxSlide.addText(step.description, { 
              x: 1.15, y: yPos + 0.25, w: textWidth - 0.65, h: 0.25, 
              fontSize: 10, color: textColor
            });
          });
        }
      } else if (slide.type === "comparison" && slide.comparison) {
        pptxSlide.addText(slide.title, { 
          x: 0.5, y: 0.3, w: textWidth, h: 0.6, 
          fontSize: 24, bold: true, color: titleColor
        });
        const colWidth = 2.3;
        const colGap = 0.2;
        const startX1 = 0.5;
        const startX2 = startX1 + colWidth + colGap;
        const itemCount = slide.comparison.items.length;
        const availableHeight = 3.6;
        const cardHeight = Math.min(0.9, (availableHeight - 0.5) / itemCount);
        const cardGap = 0.1;
        
        pptxSlide.addText(slide.comparison.leftTitle, { 
          x: startX1, y: 1.0, w: colWidth, h: 0.35, 
          fontSize: 12, bold: true, color: titleColor
        });
        pptxSlide.addText(slide.comparison.rightTitle, { 
          x: startX2, y: 1.0, w: colWidth, h: 0.35, 
          fontSize: 12, bold: true, color: titleColor
        });
        
        const cardFillTransparency = 85;
        
        slide.comparison.items.forEach((item, i) => {
          const yPos = 1.4 + (i * (cardHeight + cardGap));
          
          pptxSlide.addShape(pptx.ShapeType.roundRect, {
            x: startX1, y: yPos, w: colWidth, h: cardHeight,
            fill: { color: 'FFFFFF', transparency: cardFillTransparency },
            line: { width: 0 },
          });
          pptxSlide.addText(item.label, { 
            x: startX1 + 0.1, y: yPos + 0.05, w: colWidth - 0.2, h: 0.2, 
            fontSize: 9, bold: true, color: secondaryTextColor, valign: 'top'
          });
          pptxSlide.addText(item.left, { 
            x: startX1 + 0.1, y: yPos + 0.28, w: colWidth - 0.2, h: cardHeight - 0.35, 
            fontSize: 9, color: textColor, valign: 'top'
          });
          
          pptxSlide.addShape(pptx.ShapeType.roundRect, {
            x: startX2, y: yPos, w: colWidth, h: cardHeight,
            fill: { color: 'FFFFFF', transparency: cardFillTransparency },
            line: { width: 0 },
          });
          pptxSlide.addText(item.label, { 
            x: startX2 + 0.1, y: yPos + 0.05, w: colWidth - 0.2, h: 0.2, 
            fontSize: 9, bold: true, color: secondaryTextColor, valign: 'top'
          });
          pptxSlide.addText(item.right, { 
            x: startX2 + 0.1, y: yPos + 0.28, w: colWidth - 0.2, h: cardHeight - 0.35, 
            fontSize: 9, color: textColor, valign: 'top'
          });
        });
      } else if (slide.type === "columns" && slide.columns && slide.columns.length > 0) {
        pptxSlide.addText(slide.title, { 
          x: 0.5, y: 0.5, w: textWidth, h: 0.75, 
          fontSize: 28, bold: true, color: titleColor
        });
        const colCount = Math.max(slide.columns.length, 1);
        const colWidth = (textWidth - 0.4) / colCount;
        slide.columns.forEach((col, i) => {
          const xPos = 0.5 + (i * (colWidth + 0.2));
          pptxSlide.addText(col.heading.toUpperCase(), { 
            x: xPos, y: 1.4, w: colWidth, h: 0.4, 
            fontSize: 12, bold: true, color: titleColor
          });
          pptxSlide.addText(col.body, { 
            x: xPos, y: 1.85, w: colWidth, h: 2.5, 
            fontSize: 10, color: secondaryTextColor
          });
        });
      } else if (slide.type === "sections" && slide.sections && slide.sections.length > 0) {
        pptxSlide.addText(slide.title, { 
          x: 0.5, y: 0.5, w: textWidth, h: 0.75, 
          fontSize: 28, bold: true, color: titleColor
        });
        let yOffset = 1.4;
        slide.sections.forEach((section) => {
          pptxSlide.addText(section.heading.toUpperCase(), { 
            x: 0.5, y: yOffset, w: textWidth, h: 0.35, 
            fontSize: 12, bold: true, color: titleColor
          });
          pptxSlide.addText(section.body, { 
            x: 0.5, y: yOffset + 0.35, w: textWidth, h: 0.5, 
            fontSize: 10, color: secondaryTextColor
          });
          yOffset += 0.95;
        });
        if (slide.callout) {
          pptxSlide.addShape(pptx.ShapeType.roundRect, {
            x: 0.5, y: yOffset + 0.1, w: textWidth, h: 0.7,
            fill: { color: '000000', transparency: 70 },
            line: { width: 0 },
          });
          pptxSlide.addText(slide.callout.title.toUpperCase(), { 
            x: 0.6, y: yOffset + 0.15, w: textWidth - 0.2, h: 0.25, 
            fontSize: 10, bold: true, color: buttonBgColor
          });
          pptxSlide.addText(slide.callout.body, { 
            x: 0.6, y: yOffset + 0.4, w: textWidth - 0.2, h: 0.35, 
            fontSize: 10, color: textColor
          });
        }
      } else if (slide.type === "grid" && slide.grid && slide.grid.length > 0) {
        pptxSlide.addText(slide.title, { 
          x: 0.5, y: 0.5, w: textWidth, h: 0.75, 
          fontSize: 28, bold: true, color: titleColor
        });
        const gridColWidth = (textWidth - 0.3) / 2;
        const gridRowHeight = 1.2;
        slide.grid.forEach((item, i) => {
          const col = i % 2;
          const row = Math.floor(i / 2);
          const xPos = 0.5 + (col * (gridColWidth + 0.3));
          const yPos = 1.4 + (row * gridRowHeight);
          pptxSlide.addText(item.title.toUpperCase(), { 
            x: xPos, y: yPos, w: gridColWidth, h: 0.35, 
            fontSize: 11, bold: true, color: titleColor
          });
          pptxSlide.addText(item.description, { 
            x: xPos, y: yPos + 0.35, w: gridColWidth, h: 0.7, 
            fontSize: 9, color: secondaryTextColor
          });
        });
        if (slide.callout) {
          const calloutY = 1.4 + (Math.ceil(slide.grid.length / 2) * gridRowHeight) + 0.1;
          pptxSlide.addShape(pptx.ShapeType.roundRect, {
            x: 0.5, y: calloutY, w: textWidth, h: 0.7,
            fill: { color: '000000', transparency: 60 },
            line: { width: 0 },
          });
          pptxSlide.addText(slide.callout.title.toUpperCase(), { 
            x: 0.6, y: calloutY + 0.08, w: textWidth - 0.2, h: 0.25, 
            fontSize: 10, bold: true, color: buttonBgColor
          });
          pptxSlide.addText(slide.callout.body, { 
            x: 0.6, y: calloutY + 0.35, w: textWidth - 0.2, h: 0.3, 
            fontSize: 10, color: textColor
          });
        }
      } else if (slide.type === "cards" && slide.cards && slide.cards.length > 0) {
        pptxSlide.addText(slide.title, { 
          x: 0.5, y: 0.5, w: textWidth, h: 0.75, 
          fontSize: 28, bold: true, color: titleColor
        });
        const cardCount = slide.cards.length;
        const cardWidth = (textWidth - (cardCount - 1) * 0.2) / cardCount;
        const cardHeight = 3.0;
        
        const iconSymbols: Record<string, string> = {
          Shield: '\u2693', Zap: '\u26A1', Users: '\u263A', Clock: '\u23F0', Target: '\u25CE',
          Settings: '\u2699', TrendingUp: '\u2197', Lock: '\u26BF', CheckCircle: '\u2714', Star: '\u2605',
          Sparkles: '\u2728', Heart: '\u2665', Globe: '\u25CF', Lightbulb: '\u2736', Award: '\u2606',
          Rocket: '\u2B50', Database: '\u25A0', Code: '\u2318', Server: '\u25A3', Layers: '\u29C9', Activity: '\u26A1'
        };
        
        slide.cards.forEach((card, i) => {
          const xPos = 0.5 + i * (cardWidth + 0.2);
          const yPos = 1.3;
          
          pptxSlide.addShape(pptx.ShapeType.roundRect, {
            x: xPos, y: yPos, w: cardWidth, h: cardHeight,
            fill: { color: primaryColor, transparency: 80 },
            line: { color: primaryColor, transparency: 70, width: 0.5 },
          });
          
          pptxSlide.addShape(pptx.ShapeType.ellipse, {
            x: xPos + (cardWidth - 0.5) / 2, y: yPos + 0.15, w: 0.5, h: 0.5,
            fill: { color: primaryColor, transparency: 70 },
            line: { color: primaryColor, transparency: 40, width: 1 },
          });
          
          const iconChar = iconSymbols[card.icon] || '\u2605';
          pptxSlide.addText(iconChar, {
            x: xPos + (cardWidth - 0.5) / 2, y: yPos + 0.15, w: 0.5, h: 0.5,
            fontSize: 18, bold: true, align: 'center', valign: 'middle',
            color: textColor
          });
          
          pptxSlide.addText(card.title, { 
            x: xPos + 0.1, y: yPos + 0.8, w: cardWidth - 0.2, h: 0.5, 
            fontSize: 11, bold: true, color: textColor, align: 'center', valign: 'top'
          });
          pptxSlide.addText(card.description, { 
            x: xPos + 0.1, y: yPos + 1.35, w: cardWidth - 0.2, h: 1.5, 
            fontSize: 9, color: secondaryTextColor, valign: 'top'
          });
        });
      } else if (slide.type === "horizontal-steps" && slide.horizontalSteps && slide.horizontalSteps.length > 0) {
        pptxSlide.addText(slide.title, { 
          x: 0.5, y: 0.3, w: textWidth, h: 0.5, 
          fontSize: 24, bold: true, color: titleColor
        });
        if (slide.subtitle) {
          pptxSlide.addText(slide.subtitle, { 
            x: 0.5, y: 0.8, w: textWidth, h: 0.3, 
            fontSize: 11, color: secondaryTextColor
          });
        }
        
        const stepCount = slide.horizontalSteps.length;
        const stepWidth = textWidth / stepCount;
        const startY = 1.2;
        
        slide.horizontalSteps.forEach((step, i) => {
          const xPos = 0.5 + i * stepWidth;
          
          if (i > 0) {
            pptxSlide.addShape(pptx.ShapeType.line, {
              x: xPos, y: startY, w: 0, h: 2.5,
              line: { color: secondaryTextColor, transparency: 50, width: 1 }
            });
          }
          
          pptxSlide.addText(step.number, { 
            x: xPos + 0.1, y: startY, w: stepWidth - 0.2, h: 0.3, 
            fontSize: 10, color: secondaryTextColor
          });
          pptxSlide.addText(step.title, { 
            x: xPos + 0.1, y: startY + 0.35, w: stepWidth - 0.2, h: 0.4, 
            fontSize: 12, bold: true, color: textColor
          });
          pptxSlide.addText(step.description, { 
            x: xPos + 0.1, y: startY + 0.8, w: stepWidth - 0.2, h: 1.5, 
            fontSize: 9, color: secondaryTextColor, valign: 'top'
          });
        });
        
        if (slide.callout && slide.callout.title && slide.callout.body) {
          pptxSlide.addShape(pptx.ShapeType.roundRect, {
            x: 0.5, y: 4.0, w: textWidth, h: 0.8,
            fill: { color: primaryColor, transparency: 85 },
            line: { width: 0 },
          });
          pptxSlide.addText(`${slide.callout.title} - ${slide.callout.body}`, { 
            x: 0.6, y: 4.1, w: textWidth - 0.2, h: 0.6, 
            fontSize: 9, color: textColor
          });
        }
      } else if (slide.type === "numbered-cards" && slide.numberedCards && slide.numberedCards.length > 0) {
        pptxSlide.addText(slide.title, { 
          x: 0.5, y: 0.3, w: textWidth, h: 0.5, 
          fontSize: 24, bold: true, color: titleColor
        });
        if (slide.subtitle) {
          pptxSlide.addText(slide.subtitle, { 
            x: 0.5, y: 0.8, w: textWidth, h: 0.3, 
            fontSize: 11, color: secondaryTextColor
          });
        }
        
        const cols = 2;
        const cardWidth = (textWidth - 0.2) / cols;
        const cardHeight = 1.5;
        const startY = 1.3;
        const cardGap = 0.2;
        
        slide.numberedCards.forEach((card, i) => {
          const col = i % cols;
          const row = Math.floor(i / cols);
          const xPos = 0.5 + col * (cardWidth + cardGap);
          const yPos = startY + row * (cardHeight + cardGap + 0.15);
          
          pptxSlide.addShape(pptx.ShapeType.roundRect, {
            x: xPos, y: yPos, w: cardWidth, h: cardHeight,
            fill: { color: primaryColor, transparency: 80 },
            line: { color: primaryColor, transparency: 70, width: 0.5 },
          });
          
          pptxSlide.addShape(pptx.ShapeType.ellipse, {
            x: xPos + 0.15, y: yPos - 0.18, w: 0.4, h: 0.4,
            fill: { color: primaryColor },
            line: { color: primaryColor, transparency: 40, width: 1 },
          });
          pptxSlide.addText(String(card.number), {
            x: xPos + 0.15, y: yPos - 0.18, w: 0.4, h: 0.4,
            fontSize: 11, bold: true, align: 'center', valign: 'middle',
            color: buttonTextColor
          });
          
          pptxSlide.addText(card.title, { 
            x: xPos + 0.15, y: yPos + 0.35, w: cardWidth - 0.3, h: 0.35, 
            fontSize: 11, bold: true, color: textColor
          });
          pptxSlide.addText(card.description, { 
            x: xPos + 0.15, y: yPos + 0.7, w: cardWidth - 0.3, h: cardHeight - 0.85, 
            fontSize: 9, color: secondaryTextColor, valign: 'top'
          });
        });
      }
      
      if (slide.image?.url) {
        try {
          pptxSlide.addImage({
            data: slide.image.url,
            x: imageX,
            y: imageY,
            w: imageW,
            h: imageH,
          });
        } catch (e) {
          console.error("Failed to add image to slide:", e);
        }
      }
    }

    pptx.writeFile({ fileName: "AI_Generated_Presentation.pptx" });
    toast({
      title: "Export Complete",
      description: "Your presentation has been downloaded",
    });
  };

  const handleSlideUpdate = useCallback((updatedSlide: Slide) => {
    setSlides(prev => prev.map(s => s.id === updatedSlide.id ? updatedSlide : s));
  }, []);

  return (
    <div className="min-h-screen bg-background">
      <header className="h-16 border-b border-border flex items-center justify-between gap-4 px-6 sticky top-0 bg-background z-50">
        <div className="flex items-center gap-3">
          <Button variant="ghost" size="icon" onClick={handleBack} data-testid="button-back">
            <ArrowLeft className="h-5 w-5" />
          </Button>
          <div className="w-9 h-9 rounded-md bg-primary flex items-center justify-center">
            <Presentation className="h-5 w-5 text-primary-foreground" />
          </div>
          <h1 className="text-xl font-semibold">
            {pageState === "processing" ? "Generating..." : "Your Presentation"}
          </h1>
        </div>
        <ThemeToggle />
      </header>

      <main className="max-w-7xl mx-auto px-6 py-8">
        {pageState === "processing" && (
          <div className="max-w-2xl mx-auto space-y-8">
            <div className="text-center">
              <h2 className="text-2xl font-bold mb-2" data-testid="text-generating-title">Creating your presentation</h2>
              <p className="text-muted-foreground" data-testid="text-generating-subtitle">
                Please wait while AI generates your slides
              </p>
            </div>

            <Card className="p-6">
              <ProgressBar progress={progress} status={status} />
            </Card>

            <div className="flex justify-center">
              <Button variant="outline" onClick={handleBack} data-testid="button-cancel">
                Cancel
              </Button>
            </div>
          </div>
        )}

        {pageState === "results" && slides.length > 0 && (
          <div className="space-y-6">
            <div className="flex flex-col items-center gap-4">
              <div className="flex items-center gap-3">
                <h2 className="text-2xl font-semibold" data-testid="text-preview-title">Preview</h2>
                {autoGeneratingImages && (
                  <div className="flex items-center gap-2 text-sm text-muted-foreground bg-muted px-3 py-1 rounded-full">
                    <Loader2 className="h-3 w-3 animate-spin" />
                    <span data-testid="text-image-progress">
                      Generating images ({imageProgress.current}/{imageProgress.total})
                    </span>
                  </div>
                )}
              </div>
              <div className="flex items-center gap-2">
                <Button variant="outline" onClick={handleNewPresentation} data-testid="button-new">
                  <RefreshCw className="h-4 w-4 mr-2" />
                  New
                </Button>
                <Button onClick={handleExport} data-testid="button-export">
                  <Download className="h-4 w-4 mr-2" />
                  Export PPTX
                </Button>
              </div>
            </div>

            <div className="max-w-6xl mx-auto">
              <SlidePreview
                slide={slides[currentSlideIndex]}
                currentIndex={currentSlideIndex}
                totalSlides={slides.length}
                onPrevious={() => setCurrentSlideIndex(i => Math.max(0, i - 1))}
                onNext={() => setCurrentSlideIndex(i => Math.min(slides.length - 1, i + 1))}
                onGenerateImage={() => handleGenerateImage(slides[currentSlideIndex].id)}
                isGeneratingImage={generatingImageFor === slides[currentSlideIndex].id}
                theme={selectedTheme}
                onSlideUpdate={handleSlideUpdate}
              />
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
