import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { FileText, List, Network, Bot, ArrowLeft, Sparkles, Loader2, Search } from 'lucide-react';
import { VideoPlayer } from './VideoPlayer';
import { SummaryOutput } from './SummaryOutput';
import { TranscriptOutput } from './TranscriptOutput';
import { MindMapOutput } from './MindMapOutput';
import { AIChat } from './AIChat';
import { useVideoContext } from './VideoContext';
import { useToast } from '@/hooks/use-toast';

export const VideoResults: React.FC = () => {
  const { videoFile, setCurrentStep, isProcessing, setIsProcessing, setSummary } = useVideoContext();
  const [activeTab, setActiveTab] = useState('summary');
  const { toast } = useToast();
  const navigate = useNavigate();
  
  const handleBack = () => {
    setCurrentStep('upload');
  };

  const handleAnalyze = () => {
    if (videoFile) {
      // Pass both the blob URL and video ID
      navigate('/app/video-analysis', {
        state: { 
          video_id: videoFile.id,
          video_url: videoFile.type === 'youtube' ? videoFile.url : undefined,
          blob_url: videoFile.type === 'file' ? videoFile.url : undefined
        }
      });
    }
  };
  
  const handleGenerateSummary = () => {
    setIsProcessing(true);
    setSummary(null);
    
    setTimeout(() => {
      setSummary("This is a simulated video summary. In a real application, this would be generated by an AI service that analyzes the video content. The summary would include key points, main topics discussed, and important timestamps from the video.");
      setIsProcessing(false);
      
      toast({
        title: "Summary complete",
        description: "Your video has been summarized successfully"
      });
    }, 3000);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <Button variant="outline" onClick={handleBack} className="flex items-center gap-2 rounded-full px-4">
          <ArrowLeft className="h-4 w-4" />
          Back to Upload
        </Button>
        
        <div className="flex items-center gap-2">
          <Button
            variant="secondary"
            onClick={handleAnalyze}
            className="flex items-center gap-2 rounded-full px-4"
          >
            <Search className="h-4 w-4" />
            Analyze Video
          </Button>
          
          <Button 
            onClick={handleGenerateSummary}
            disabled={isProcessing}
            className="gradient-button rounded-full"
          >
            {isProcessing ? (
              <>
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                Processing...
              </>
            ) : (
              <>
                <Sparkles className="h-4 w-4 mr-2" />
                Generate Summary
              </>
            )}
          </Button>
        </div>
      </div>
      
      <div className="glass-panel rounded-xl p-4 border border-primary/10 max-w-xl mx-auto">
        <VideoPlayer 
          videoId={videoFile?.id}
          videoUrl={videoFile?.url}
          className="w-full" 
        />
      </div>
      
      <Card className="figma-card overflow-visible">
        <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
          <TabsList className="grid grid-cols-4 rounded-full p-1 bg-muted/50 mb-6 max-w-xl mx-auto">
            <TabsTrigger value="summary" className="rounded-full flex items-center gap-2">
              <List className="h-4 w-4" />
              <span>Summary</span>
            </TabsTrigger>
            <TabsTrigger value="transcript" className="rounded-full flex items-center gap-2">
              <FileText className="h-4 w-4" />
              <span>Transcript</span>
            </TabsTrigger>
            <TabsTrigger value="mindmap" className="rounded-full flex items-center gap-2">
              <Network className="h-4 w-4" />
              <span>Mind Map</span>
            </TabsTrigger>
            <TabsTrigger value="aichat" className="rounded-full flex items-center gap-2">
              <Bot className="h-4 w-4" />
              <span>AI Chat</span>
            </TabsTrigger>
          </TabsList>
          
          <TabsContent value="summary" className="mt-0">
            <SummaryOutput videoId={videoFile?.id || ''} />
          </TabsContent>
          
          <TabsContent value="transcript" className="mt-0">
            <TranscriptOutput videoId={videoFile?.id || ''} />
          </TabsContent>
          
          <TabsContent value="mindmap" className="mt-0">
            <MindMapOutput 
              videoId={videoFile?.id || ''}
              mindMapData={null}
              loading={false}
              error={null}
            />
          </TabsContent>
          
          <TabsContent value="aichat" className="mt-0">
            <AIChat videoId={videoFile?.id || ''} />
          </TabsContent>
        </Tabs>
      </Card>
    </div>
  );
};
