// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vusjibqsihfeuscntbje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1c2ppYnFzaWhmZXVzY250YmplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTE4MDcsImV4cCI6MjA2OTcyNzgwN30.T9-L5yx3XlbGwSMmqvKimkYj6fo7WuTCRlGsOYY50OQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    options: {
      redirectTo: window.location.origin,
      siteName: 'Quizano',
    }
  },
});